first_finger:
  kinematics_solver: hand_ik_coupling_plugin/HandIKCouplingPlugin
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  maxIterations: 100
  epsilon: 0.001
  root_name: rh_palm
  tip_name: rh_fftip
middle_finger:
  kinematics_solver: hand_ik_coupling_plugin/HandIKCouplingPlugin
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  maxIterations: 100
  epsilon: 0.001
  root_name: rh_palm
  tip_name: rh_mftip
ring_finger:
  kinematics_solver: hand_ik_coupling_plugin/HandIKCouplingPlugin
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  maxIterations: 100
  epsilon: 0.001
  root_name: rh_palm
  tip_name: rh_rftip
little_finger:
  kinematics_solver: hand_ik_coupling_plugin/HandIKCouplingPlugin
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  maxIterations: 100
  epsilon: 0.001
  root_name: rh_palm
  tip_name: rh_lftip
thumb:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  position_only_ik: true
  root_name: rh_palm
  tip_name: rh_thtip